export const initialItems = [
  {
    id: 1,
    fromFramework: true,
    text: "Matéria e energia",
    type: "topic",
    subTitle: "Tópico",
    children: [
      {
        id: 10,
        fromFramework: true,
        text: "Propriedades e usos dos materiais",
        type: "topic",
        subTitle: "Tópico - Matéria e energia",
        children: [
          {
            id: 100,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Identificar de que materiais são feitos os objetos que fazem parte da vida cotidiana",
            type: "goal",
            children: [],
          },
          {
            id: 101,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Investigar a produção de diferentes objetos cotidianos de uma perspectiva histórica",
            type: "goal",
            children: [],
          },
          {
            id: 102,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Construir objetos de acordo com instruções",
            type: "goal",
            children: [],
          },
          {
            id: 103,
            fromFramework: true,
            text: "Consumo Consciente",
            type: "topic",
            subTitle: "Tópico - Propriedades e usos dos materiais",
            children: [
              {
                id: 1030,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Compreender que o uso sustentável da água está relacionado a aspectos da saúde individual e coletiva",
                type: "goal",
                children: [],
              },
              {
                id: 1031,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Discutir formas sustentáveis da utilização da água",
                type: "goal",
                children: [],
              },
              {
                id: 1032,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Propor soluções sustentáveis para o uso da água",
                type: "goal",
                children: [],
              },
            ],
          },
          {
            id: 104,
            fromFramework: true,
            text: "Reciclagem",
            type: "topic",
            subTitle: "Tópico - Propriedades e usos dos materiais",
            children: [
              {
                id: 1040,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Investigar bioconstruções ecológicas",
                type: "goal",
                children: [],
              },
              {
                id: 1041,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Construir propostas coletivas para um consumo mais consciente na escola",
                type: "goal",
                children: [],
              },
              {
                id: 1042,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Criar soluções tecnológicas para o descarte adequado dos materiais consumidos na escola",
                type: "goal",
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
