export const initialItems = [
  {
    id: 1,
    fromFramework: true,
    text: "Matéria e energia",
    type: "topic",
    subTitle: "Tópico",
    children: [
      {
        id: 10,
        fromFramework: true,
        text: "Propriedades e usos dos materiais",
        type: "topic",
        subTitle: "Tópico - Matéria e energia",
        children: [
          {
            id: 100,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Identificar de que materiais são feitos os objetos que fazem parte da vida cotidiana",
            type: "goal",
            children: [],
          },
          {
            id: 101,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Identificar como os objetos que fazem parte da vida cotidiana são utilizados",
            type: "goal",
            children: [],
          },
          {
            id: 102,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Identificar com quais materiais eram produzidos os objetos que fazem parte da vida cotidiana no passado",
            type: "goal",
            children: [],
          },
          {
            id: 103,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Investigar a produção de diferentes objetos cotidianos de uma perspectiva histórica",
            type: "goal",
            children: [],
          },
          {
            id: 104,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Identificar os materiais envolvidos na produção de objetos associados a cultura local",
            type: "goal",
            children: [],
          },
          {
            id: 105,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Construir objetos de acordo com instruções",
            type: "goal",
            children: [],
          },
          {
            id: 106,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Reconhecer quais os riscos envolvidos na utilização de diferentes materiais para a produção de objetos da vida cotidiana",
            type: "goal",
            children: [],
          },
          {
            id: 107,
            fromFramework: true,
            subTitle: "Objetivo - Propriedades e usos dos materiais",
            text: "Reconhecer que as partes que compõem um objeto podem ser reorganizadas em um novo objeto",
            type: "goal",
            children: [],
          },
          {
            id: 108,
            fromFramework: true,
            text: "Consumo Consciente",
            type: "topic",
            subTitle: "Tópico - Propriedades e usos dos materiais",
            children: [
              {
                id: 1080,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Identificar os principais usos da água nas atividades cotidianas",
                type: "goal",
                children: [],
              },
              {
                id: 1081,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Identificar ações humanas que auxiliam no controle da poluição da água",
                type: "goal",
                children: [],
              },
              {
                id: 1082,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Compreender que o uso sustentável da água está relacionado a aspectos da saúde individual e coletiva",
                type: "goal",
                children: [],
              },
              {
                id: 1083,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Discutir formas sustentáveis da utilização da água",
                type: "goal",
                children: [],
              },
              {
                id: 1084,
                fromFramework: true,
                subTitle: "Objetivo - Consumo Consciente",
                text: "Propor soluções sustentáveis para o uso da água",
                type: "goal",
                children: [],
              },
            ],
          },
          {
            id: 109,
            fromFramework: true,
            text: "Reciclagem",
            type: "topic",
            subTitle: "Tópico - Propriedades e usos dos materiais",
            children: [
              {
                id: 1090,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Investigar bioconstruções ecológicas",
                type: "goal",
                children: [],
              },
              {
                id: 1091,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Construir propostas coletivas para um consumo mais consciente na escola",
                type: "goal",
                children: [],
              },
              {
                id: 1092,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Criar soluções tecnológicas para o descarte adequado dos materiais consumidos na escola",
                type: "goal",
                children: [],
              },
              {
                id: 1093,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Criar soluções tecnológicas para a reutilização ou reciclagem de materiais consumidos na escola",
                type: "goal",
                children: [],
              },
              {
                id: 1094,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Construir propostas coletivas para um consumo mais consciente na vida cotidiana",
                type: "goal",
                children: [],
              },
              {
                id: 1095,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Criar soluções tecnológicas para o descarte adequado dos materiais consumidos na vida cotidiana",
                type: "goal",
                children: [],
              },
              {
                id: 1096,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Criar soluções tecnológicas para a reutilização ou reciclagem de materiais consumidos na vida cotidiana",
                type: "goal",
                children: [],
              },
              {
                id: 1097,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Compreender que o descarte de materiais pode implicar em aspectos sanitários",
                type: "goal",
                children: [],
              },
              {
                id: 1098,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Reconhecer a escala de tempo na decomposição de materiais e objetos",
                type: "goal",
                children: [],
              },
              {
                id: 1099,
                fromFramework: true,
                subTitle: "Objetivo - Reciclagem",
                text: "Reconhecer o dano ambiental causado pelo consumo humano",
                type: "goal",
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
